language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
before_install:
  - go mod vendor
script:
  - go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)